De-cal/6-Favorite_Photo-FE

package-lock.json, package.json, src/app/layout.js, src/app/page.js, src/components/common/Card.jsx
- card 컴포넌트 추가하였습니다
-type(original, sorldout, for_sale, for_sale_soldout, my_card), card 객체를 받아서 type에 따라 디자인이 변경되도록 하였습니다. 
- 조건에 따라 글자 색상을 다르게 하기 위해 clsx 패키지 추가하였습니다
-
-
- P2 : 반영을 …
=> Feat/card: card 공통 컴포넌트 추가

.env.example, src/app/layout.js, src/components/common/Header.jsx, src/components/common/HeaderLayout.jsx
- Header 레이아웃 UI만 일단 구현해두었습니다. 추가적으로 추후에 작업하실 때 수정하시면 됩니다.
- Header 레이아웃 UI 구현
-
-
-
=> feat: Header 레이아웃 UI 구현

src/components/common/Header.jsx
- 이미지 이름 변경에 따른 오류가 있어서 이름만 변경했습니다.
-
-
-
-
=> refactor: 이미지 이름변경

src/app/page.js, src/components/ui/buttons/ActionButton.jsx
- 피그마 시안에 나와있는 버튼 컴포넌트 아래 부분 모두 공용으로 사용할수 있게 제작하였습니다.
- 색깔별로 pirmary, secondary 값은 'variant' 프롭스로 받을수 있게 하였고, 사용 예시는 저의 페이지 담당부분인 랜딩페이지 ('/')에 임시적으로 구현해두었습니다.
- 사용방법은 노션에 정리해두었습니다 (https://www.notion.so/1f8b498dbd8180099efdc8600c812d50?pvs=4)
피그마 시안
구현 페이지 (랜딩페이지)
-
-없음
-
-
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 …
=> feat: 공용 버튼 컴포넌트 추가

src/app/my-gallery/_components/TopSection.jsx, src/app/my-gallery/page.jsx
마이갤러리 페이지 ui작업 - 포토카드 생성 연결
>포토카드 생성 페이지와 연동
UI조금 그린거 말곤 없습니다
> "없음"
-
> 없음
-
-
=> 마이갤러리 UI작업중 

src/app/marketplace/_components/DetailCard.jsx, src/app/marketplace/_components/SellerCardInfo.jsx, src/app/marketplace/sellers/[id]/page.jsx
- 마이갤러리 생성 기능의 UI 및 기본 기능 작업
- 상세 디테일 디자인 수정, 컴포넌트 분리
- 없음
- 없음
-
=> fix: 마켓플레이스 상세페이지 디테일 수정

src/components/common/HeaderLayout.jsx
- 헤더 UI 분기 처리 다시 수정했습니다.
- 로그인, 회원가입 페이지에서는 일절 헤더 레이아웃 보이지 않도록 했습니다.
- 마켓플레이스, 랜딩 페이지에서는 헤더 전부 보이게 해두었습니다.
- 그 외의 페이지에서는 모바일일 때만 헤더 보이지 않도록 설정해두었습니다.
-
-
-
- P2 : 반영을 적극적으로 고려해 주시면 좋을 것 …
=> feat: Header 분기처리 수정

src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/page.jsx
- 마켓플레이스 구매자 페이지 일단 하던 것 까지만 PR 올렸습니다 그래서 완성본은 아닌 점 참고 부탁드립니다!
-
-
-
-
=> feat: 마켓플레이스 구매자 UI 1차 구현

src/app/marketplace/_components/Search.jsx, src/app/marketplace/page.jsx
-
- 반응형 frontend 의 수정사항이 반영되었습니다.
- 없음
-
- 
=> Feat/marketplace home UI

src/app/my-gallery/_components/PageNation.jsx, src/app/my-gallery/page.jsx, src/app/my-sell/_components/Dropdown.jsx, src/app/my-sell/_components/PageNation.jsx, src/app/my-sell/_components/PhotoCardSection.jsx, src/app/my-sell/_components/RankDiv.jsx, src/app/my-sell/_components/RankSection.jsx, src/app/my-sell/_components/SortAndSearchSection.jsx, src/app/my-sell/_components/TopSection.jsx, src/app/my-sell/page.jsx, src/assets/icons/ic-left-gray.svg, src/assets/icons/ic-right-gray.svg
> 마이갤러리 및 나의판매목록 페이지 완성...?
> 필터링 및 검색기능 구현
> 페이지네이션은 API설계 시 수정 예정 
> 필터링 및 검색 시 데이터가 없을때 안내DIV추가
> 등급부분 모바일뷰에서 스크롤기능 동작하게 구현(스크롤은 안보이게)
-
> 마이갤러리 및 나의판매목록 FE-UI작업 대부분 완료
-
> 없음
-
> 딱히없음.
-
-
=> feat: 마이갤러리페이지 및 나의판매목록페이지 완성

src/app/my-gallery/create/page.jsx, src/components/ui/buttons/ActionButton.jsx
- 마이포토카드 생성 디테일한 부분 수정
- pc, 테블릿 버전 적용
- 버튼 disabled 기능 추가
- 버튼 컴포넌트의 variantStyles에 upload추가
- 버튼 컴포넌트의 variantStyles에 upload추가
-
-
-
- P3 : …
=> fix: 마이갤러리 포토카드 생성 디테일 & 버튼컴포넌트 추가

src/components/common/HeaderLayout.jsx
- Header 레이아웃 clsx에서 실수가 있어서 데스크탑 기준으로 가운데 정렬이 되어있지 않았었는데 그 부분 가운데로 정렬되도록 수정했습니다.
-
-
-
-
=> feat: Header 레이아웃 수정

src/components/common/MobileHeader.jsx
- 모바일 Header 이미지 크기 수정 했습니다 18 -> 22
-
-
-
-
=> fix: 모바일 Header 이미지 크기 수정

src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/page.jsx
- 마켓 플레이스 구매자 2차적으로 UI 완성 했습니다. 90% 완성입니다.
-
-
-
-
=> feat: 마켓플레이스 구매자 2차 UI 완성

src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx
=> refactor: 구매자 페이지 랭크 리팩터링

src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SelectExchangePhotoCardModal .jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/page.jsx, src/components/common/MobileHeader.jsx
- 교환 모달 1차 완성 했습니다. 미완성이라서 감안해주세요.
- 수빈님이 만드신 mobile 헤더의 위치를 수정했습니다.
-
-
-
-
=> feat: 교환 모달 1차 UI 작업, mobileHeader 위치 수정

src/components/common/HeaderLayout.jsx, src/components/modal/notification/Notification.jsx, src/components/modal/notification/NotificationCard.jsx, src/components/modal/notification/NotificationsModal.jsx, src/components/modal/notification/NotificationsModalMobile.jsx, src/components/modal/notification/mock_data.json, src/components/modal/randomPoint/RandomBoxCard.jsx, src/components/modal/randomPoint/RewardPoint.jsx
- 헤더 내의 종모양 알림 아이콘을 눌렀을 때 
- 모바일 환경에선 전체 화면으로 꽉차게 알림 리스트가 보입니다.
- 태블릿이나 데스크탑 환경에선 종모양 알림 아이콘 밑에 붙어서 보입니다.
- 원래 HeaderLayout 안에 있던 종모양 알림 아이콘을 Notification 컴포넌트로 옮기고 Notification컴포넌트를 임포트 해놓았습니다.
- 구현 과정에서 useModal 과 MobileHeader 를 가져다 사용했습니다.
- 이미지가 svg 에서 avif로 변경 했다고 들어 일단 이름만 변경 했습니다.
- 없음.
- 없음.
- Comment 작성 시 Prefix로 P1, P2, …
=> feat: 목데이터 이용한 알림 기능 UI 구현.

src/app/my-gallery/_components/MobileFilter.jsx, src/app/my-gallery/_components/PhotoCardSection.jsx, src/app/my-gallery/_components/RankSection.jsx, src/app/my-gallery/_components/SortAndSearchSection.jsx, src/app/my-gallery/page.jsx, src/app/my-sell/_components/MobileFilter.jsx, src/app/my-sell/_components/PhotoCardSection.jsx, src/app/my-sell/_components/RankSection.jsx, src/app/my-sell/_components/SortAndSearchSection.jsx, src/app/my-sell/page.jsx, src/providers/ModalProvider.jsx
마이갤러리 및 나의판매페이지 모바일 필터링 기능 구현중 
-
마이갤러리 및 나의판매페이지 모바일 필터링 기능 구현중 ->판매페이지에서 봐야 됨
-마이갤러리 및 나의판매페이지 모바일 필터링 기능 구현중 
> 모달 프로바이더 ref(백그라운드) 클릭시 모달 닫힘 기능 개선 (원래안됏던거 고침)
-
-
-
=> 마이갤러리 및 나의판매페이지 모바일 필터링 기능 구현중 

src/app/my-gallery/create/_components/TopSection.jsx, src/app/my-gallery/create/page.jsx
-
- 생성페이지 검증 기능 추가
- 숫자만 입력 가능하도록(문자,기호 입력시 경고 문구)
- 마이너스 입력 불가
- 없음
-
-
=> feat:생성페이지 검증

src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx, src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx, src/components/common/Desktop.jsx, src/components/common/Mobile.jsx, src/components/common/Tablet.jsx
- 마켓플레이스 구매자 교환 모달 UI 90% 완성했습니다.
-
-
-
-
=> feat: 마켓플레이스 구매자 교환 모달 2차 UI 완성

src/app/marketplace/buyers/[id]/_components/ExchangeInputModal.jsx, src/providers/ModalProvider.jsx
- 교환 모달 완성했습니다(교환 카드 선택 후 모달입니다.)
-
-
-
-
=> feat: 구매자 교환 모달 완성

src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SelectExchangePhotoCardModal .jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
- 마켓 플레이스 구매자 모달 UI 80% 완성입니다. 추후에 민경님 모달 붙일거고, 카드 컴포넌트 만들어야 합니다.
- commit이 하나인 점 죄송합니다.
-
-
-
-
=> feat: 마켓플레이스 구매자 모달 UI 2차 완성

src/app/marketplace/_components/Search.jsx, src/app/marketplace/page.jsx
-
- 마켓페이지에 검색기능과 필터 컴포넌트 추가
-
-
-
=> feat: marketplace 검색과 필터 기능 적용

src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/buyers/[id]/_components/MyExchangeOffers.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
=> feat: 마켓플레이스 구매자 UI 3차 완성(95%)

src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx
- 프리티어 재설정에 따른 코드 포매팅
- 그냥 간단하게 연결 작업 정도?
-
-
-
-
=> feat: 마켓플레이스 구매자 자잘한 수정

src/app/marketplace/_components/SortDropdown.jsx, src/app/marketplace/page.jsx, src/app/marketplace/sellers/[id]/_components/DetailCard.jsx, src/app/marketplace/sellers/[id]/_components/ExchangeCards.jsx, src/app/marketplace/sellers/[id]/page.jsx
- 마켓플레이스 드롭다운 구현완료 
- 판매 페이지 교환 제시 목록 구현 진행 중
-  DetailCard.jsx 에 조건부 렌더링 추가 했습니다.
-
-
-
=> Feat/marketplace sort 드롭 다운 구현 완료 & 판매 페이지 교환 제시 목록 구현 진행 중

src/app/my-gallery/[id]/_components/CardInfo.jsx, src/app/my-gallery/[id]/_components/TopTitle.jsx, src/app/my-gallery/[id]/page.jsx, src/app/my-gallery/_components/Dropdown.jsx, src/app/my-gallery/_components/RankDiv.jsx, src/app/my-gallery/_components/RankSection.jsx, src/app/my-gallery/page.jsx, src/app/my-sell/_components/Dropdown.jsx, src/app/my-sell/_components/RankDiv.jsx, src/app/my-sell/_components/RankSection.jsx, src/app/my-sell/page.jsx
-
> 마이갤러리 및 나의판매페이지 랭크섹션 세부 조정
> 마이갤러리 상세페이지
-
-
-
-
=> Feat/my gallary - 마이갤러리 상세페이지 제작 및 랭크 세부 조정

src/components/common/HeaderLayout.jsx, src/components/modal/notification/Notification.jsx
- 헤더 내에 알림 모달과 프로필 모달 동시에 켜지지 않도록 처리.
- 하나가 켜지면 다른건 꺼지도록.
- Notification 컴포넌트 안에서 관리하던 알림 모달 상태값을 HeaderLayout 컴포넌트에서 관리.
- 없음.
- 그냥 setState(false)로 구현했는데, 혹시 다른 좋은 방법이 있다면 말씀 주세요.
- 없음. …
=> feat: 헤더 내 모달 동시동작 제거.

src/api/point.js, src/components/modal/randomPoint/RewardPoint.jsx, src/components/modal/randomPoint/SurprisePointModal.jsx, src/hooks/useInactiveTimer.js, src/hooks/useRandomPointTimer.js
- 타이머가 다 되면 깜짝 모달이 열리고 상자 선택시 포인트를 지급합니다.
- api 코드 추가하여 BE api와 연동했습니다.
- 쿠키 패치 함수를 활용하여 랜덤 포인트 지급시 유저 테이블에 포인트가 추가 되는 것을 확인 했습니다.
- 리액트쿼리(tanstackQuery) 적용했습니다.(useMutation)
- 비활동시 타이머를 초기화 하는 함수를 다시 적용했습니다.
- 테스트를 위해서 포인트 타이머는 30초, 비활성화 타이머는 20초로 설정해놨습니다.
- 30초 타이머 이내에 20초 이상 활동이 없으면 타이머가 초기화 됩니다.
- 활동 예시 : 마우스 무브, 키프레스, 스크롤, 클릭
- 없음.
- 없음.
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 3일 …
=> Feat/point api 코드 추가 및 연동, useMutaion 으로 리팩토링.

src/components/modal/randomPoint/RewardPoint.jsx, src/components/modal/randomPoint/SurprisePointModal.jsx
- 포인트 받은 후 헤더 모달에 내가 가진 포인트 리렌더링을 위해 getUser 함수 호출.
- 랜덤 포인트 모달이 뜨고, 비활성화 되는 함수 내에 로그인 했는지 여부를 authProvider에서 가져다가 사용.
- 랜덤 포인트 지급 api 호출 성공시 authProvider속 getUser 함수 사용으로 최신화 로직 추가.
- 멘토님이 언급해주신 선택 완료 버튼에 cursor-pointer 추가.
- 없음.
- 없음.
- P1 : 꼭 반영해 …
=> feat/point 포인트 내에서 auth 관련 코드 추가. 

src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/_components/SelectPhotoCardsModal.jsx, src/app/marketplace/buyers/[id]/_components/MyExchangeOffer.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/_components/modal/BuyPhotoCardModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx, src/app/marketplace/buyers/[id]/page.jsx, src/lib/api/article.api.js
- 마켓플레이스 API 연동했습니다. 한 번에 여러개 보낸거라서 다른 것도 섞여있을 수 있습니다.
-
-
-
-
=> feat: 마켓플레이스 API 연동

src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/buyers/[id]/_components/PhotoCardBuyerDetail.jsx, src/app/marketplace/buyers/[id]/_components/SellerExchangeInfo.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeCancelModal.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx, src/lib/api/article.api.js
- API 연동 관련해서 작은 수정만 했습니다.
-
-
-
-
=> feat: 마켓플레이스 구매자 API 연동 관련해서 작은 수정

src/components/common/HeaderLayout.jsx, src/components/common/MobileProfileModal.jsx, src/components/common/TabletAndDesktopProfileModal.jsx
- 프로필 모달 태블릿 모달은 모바일 화면으로 이동하면 자동으로 닫히도록, 모바일 모달은 태블릿 이상이면 자동으로 닫히도록 수정했습니다.
-
-
-
-
=> fix: 프로필 모달 화면 크기에 따라서 자동으로 닫히도록 수정

src/app/marketplace/_components/marketplace/ArticleGrid.jsx, src/app/marketplace/_components/marketplace/MarketplaceHeader.jsx, src/app/marketplace/_components/marketplace/MyCardSellBtn.jsx, src/lib/api/article.api.js
- 마켓플레이스 로그인 했을때 각 아티클들로 접근 가능하게 하는 부분 오류 수정 했습니다.
-
-
-
-
=> fix: marketplace 인가 오류 수정

src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/buyers/[id]/_components/modal/ExchangeInputModal.jsx, src/lib/api/article.api.js
- 객체 구조분해 간소화 하도록 리팩터링 진행했습니다.
- 교환 요청할 카드를 선택할 때 태블릿 버전이면, 모달이 아래에서 위로 올라오도록 애니메이션 추가
- 판매자 페이지 불러오기 cookiefetch로 변경
-
-
-
-
- P3 : 이런 방법도 있을 …
=> refactor: 객체 구조분해 간소화

next.config.mjs, src/app/marketplace/_components/ExchangeCard.jsx, src/app/marketplace/buyers/[id]/_components/MyExchangeOffer.jsx, src/app/marketplace/sellers/[id]/page.jsx, src/lib/api/article.api.js
- 구매자 상세 페이지에서 교환 목록 불러오기 구현했습니다.
-
-
-
-
=> feat: 구매자 상세 페이지 교환 목록 불러오기 구현

src/app/(auth)/_components/AuthModal.jsx, src/app/(auth)/_components/FormInput.jsx, src/app/(auth)/_components/PasswordInput.jsx, src/app/(auth)/login/page.jsx, src/app/(auth)/signup/page.jsx, src/components/common/HeaderLayout.jsx, src/components/common/MobileProfileModal.jsx, src/lib/api/fetchClient.api.js, src/lib/utils/authValidators.js
> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요  
- 유저가 회원가입 폼에서 이메일 입력시 대문자 입력이 가능했던거 수정
- 회원가입, 로그인 페이지 마진 조정 필요
- HeaderLayout `로그아웃 버튼` (모바일 모달일때도)이 클릭 가능한 UI로 인식되지 않는 문제를  해결 
- 유저가 불일치하는 비밀번호나 이메일 입력시 데이터베이스에서 오는 에러메세지가 세션이 만료되었다고 잘못 오고있었는데, 프론트에서 `cookieFetch` 할때 에러코드 처리 로직에 문제가 있어서 수정이 필요했습니다.
- 위에 상황에서 나오는 모달 디자인 개선
---
- 유저가 회원가입 폼에서 이메일 입력시 영어 대문자는 자동으로 소문자 변환됨
- 회원가입 폼에서 비밀번호 조건이 너무 취약해서 영문, 숫자, 특수문자 8자이상부터 허용하도록 개선, 그에 따른 백엔드 조정한 부분은 BE 피알에 올리겠습니다
- 회원가입, 로그인 페이지 마진 조정 완료
- `MobileProfileModal`의 로그아웃 버튼에 `cursor-pointer` 스타일을 적용해 시각적 피드백 개선
- 세빈님의 marketplace에서 나오는 로그인 필요 모달 LoginNeed 와 비슷하게 (조금 모달 크기같은 점은 제가  커스텀하였습니다) 을 login 페이지에서 구현 (유저 정보 불일치시 나옴)
---
> …
=> feat: 로그인 회원가입, 헤더레이아웃 QA 피드백 반영

src/components/common/HeaderLayout.jsx, src/providers/AuthProvider.jsx
- 로그인한 유저의 화면에서 새로고침시 헤더가 비로그인한 유저의 헤더처럼 잠시 보였던 증상 (서버에서 user 정보 불러올 동안 user의 값이 null이라서)을 개선하였습니다
- 
-없음
-없음
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 …
=> refactor: AuthProvider에 isLoading 상태값 추가, HeaderLayout에 적용

src/middleware.js
=> feat: 테스트용 미들웨어함수 추가

next.config.mjs
- chore: next.config.js 수정
-
-
-
-
=> chore: next.config.js 수정

src/app/layout.js, src/app/marketplace/[id]/buyer/page.jsx
- fix: 컨텍스트 API 프로바이더 바인딩 수정
-
-
-
-
=> fix: 컨텍스트 API 프로바이더 바인딩 수정

src/app/my-sell/_components/MobileFilter.jsx, src/app/my-sell/_components/MySell.jsx, src/providers/ModalProvider.jsx
=> fix/모바일필터 조정

src/app/marketplace/[id]/buyer/_components/PhotoCardBuyerDetail.jsx
=> feat: imgUrl 수정

src/app/marketplace/[id]/buyer/_components/modal/BuyPhotoCardModal.jsx, src/components/common/CommonModal.jsx
- fix: getUser로 모달 닫히는 현상 디버그
-
-
-
-
=> fix: getUser로 모달 닫히는 현상 디버그

src/app/marketplace/_components/marketplace/SortDropdown.jsx
=> Feat/marketplace  sort 간격 조정

src/app/marketplace/[id]/seller/_components/SellerCardInfo.jsx, src/app/marketplace/[id]/seller/page.jsx, src/app/marketplace/_components/SellPhotoCardDetailModal.jsx
- 수정하기 모달에 이미지 뜨게 바꿨습니다(간격 조정은 잘 되었는지 모르겠네요...)
-
-
-
-
=> fix: 이미지 수정

src/app/marketplace/[id]/seller/_components/SellerCardInfo.jsx, src/app/marketplace/[id]/seller/page.jsx, src/app/marketplace/_components/marketplace/MyCardSellBtn.jsx, src/app/modal-test/page.jsx, src/app/my-gallery/create/page.jsx, src/app/my-sell/_components/PhotoCardSection.jsx, src/lib/api/card.api.js, src/providers/AuthProvider.jsx, src/providers/QueryProvider.jsx
- refactor: console, alert 삭제
-
-
-
-
=> refactor: console, alert 삭제
